version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      root-npm:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "npm"
    directory: "/packages/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      web-npm:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "npm"
    directory: "/packages/functions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      functions-npm:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      shared-npm:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "npm"
    directory: "/packages/api-server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      api-server-npm:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "pub"
    directory: "/packages/mobile"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      mobile-pub:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "security"
