// File generated by FlutterFire CLI.
// ignore_for_file: type=lint, lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE99EAoGniEwCLfu4llmv_NsSjbwr-ZRE',
    appId: '1:489413148337:web:9b4e97350073a22968ac90',
    messagingSenderId: '489413148337',
    projectId: 'vehicle-vitals-prod',
    storageBucket: 'vehicle-vitals-prod.firebasestorage.app',
    measurementId: 'G-32PCGDSNT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFYAlutFG6V_h2CpzYbeq4QGjVpV4S52M',
    appId: '1:919227980868:android:afb6329906f754c6b5f011',
    messagingSenderId: '919227980868',
    projectId: 'vehicle-vitals-dev',
    storageBucket: 'vehicle-vitals-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyHtjchXulHKuwM2RANh6JxAfK7EyTWU',
    appId: '1:489413148337:ios:b55d0b37718e299368ac90',
    messagingSenderId: '489413148337',
    projectId: 'vehicle-vitals-prod',
    storageBucket: 'vehicle-vitals-prod.firebasestorage.app',
    iosBundleId: 'com.nelsongrey.vehiclevitals.app.ios',
    iosClientId:
        '489413148337-p7ocsoegok2nfnfm7rlg3oohudldlb58.apps.googleusercontent.com',
  );
}
