// File generated by FlutterFire CLI.
// DISABLED FOR TESTFLIGHT BUILD - Firebase plugins removed
// ignore_for_file: type=lint, lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// DISABLED FOR TESTFLIGHT - Using stub implementation
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static dynamic get currentPlatform {
    // Stub implementation for TestFlight
    throw UnsupportedError('Firebase disabled for TestFlight build');
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDE99EAoGniEwCLfu4llmv_NsSjbwr-ZRE',
  //   appId: '1:489413148337:web:9b4e97350073a22968ac90',
  //   messagingSenderId: '489413148337',
  //   projectId: 'vehicle-vitals-prod',
  //   storageBucket: 'vehicle-vitals-prod.firebasestorage.app',
  //   measurementId: 'G-32PCGDSNT9',
  // );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyB4yx8ABAc5XeU7fbFiz19BOcu9GCkQBvk',
  //   appId: '1:489413148337:android:0ed732a4b8cd462068ac90',
  //   messagingSenderId: '489413148337',
  //   projectId: 'vehicle-vitals-prod',
  //   storageBucket: 'vehicle-vitals-prod.firebasestorage.app',
  // );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCIyHtjchXulHKuwM2RANh6JxAfK7EyTWU',
  //   appId: '1:489413148337:ios:b55d0b37718e299368ac90',
  //   messagingSenderId: '489413148337',
  //   projectId: 'vehicle-vitals-prod',
  //   storageBucket: 'vehicle-vitals-prod.firebasestorage.app',
  //   iosBundleId: 'com.nelsongrey.vehiclevitals.app.ios',
  //   iosClientId:
  //       '489413148337-p7ocsoegok2nfnfm7rlg3oohudldlb58.apps.googleusercontent.com',
  // );
}
