import 'dart:io';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:csv/csv.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

class DataExportService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  String get _userId {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) {
      throw Exception('Not authenticated');
    }
    return user.uid;
  }

  DateTime _asDate(dynamic value) {
    if (value is Timestamp) return value.toDate();
    if (value is DateTime) return value;
    if (value is int) return DateTime.fromMillisecondsSinceEpoch(value);
    if (value is String) {
      final parsed = DateTime.tryParse(value);
      if (parsed != null) return parsed;
    }
    return DateTime.now();
  }

  String _isoDate(dynamic value) {
    return _asDate(value).toIso8601String().split('T').first;
  }

  Future<Directory> _exportDirectory() async {
    final baseDir = await getTemporaryDirectory();
    final exportDir = Directory('${baseDir.path}/exports');
    if (!await exportDir.exists()) {
      await exportDir.create(recursive: true);
    }
    return exportDir;
  }

  Future<Map<String, dynamic>?> _getVehicle(String vin) async {
    final vehicleSnapshot = await _firestore
        .collection('users')
        .doc(_userId)
        .collection('vehicles')
        .doc(vin)
        .get();
    return vehicleSnapshot.data();
  }

  // Export maintenance history as CSV
  Future<void> exportMaintenanceAsCSV(String vin) async {
    final maintenanceData = await _getMaintenanceData(vin);
    final vehicle = await _getVehicle(vin);

    final rows = <List<dynamic>>[
      <dynamic>[
        'VIN',
        'Make',
        'Model',
        'Year',
        'Title',
        'Notes',
        'Cost',
        'Date',
        'Created At',
        'Updated At',
      ],
    ];

    for (final entry in maintenanceData) {
      rows.add(<dynamic>[
        vin,
        vehicle?['make'] ?? '',
        vehicle?['model'] ?? '',
        vehicle?['year'] ?? '',
        entry['title'] ?? '',
        entry['notes'] ?? '',
        entry['cost'] ?? 0,
        _isoDate(entry['date']),
        _isoDate(entry['createdAt']),
        _isoDate(entry['updatedAt']),
      ]);
    }

    final csvContent = const ListToCsvConverter().convert(rows);
    final exportDir = await _exportDirectory();
    final fileName =
        'maintenance-$vin-${DateTime.now().millisecondsSinceEpoch}.csv';
    final file = File('${exportDir.path}/$fileName');
    await file.writeAsString(csvContent);

    await SharePlus.instance.share(
      ShareParams(
        files: [XFile(file.path)],
        subject: 'Vehicle Vitals Maintenance Export ($vin)',
        text: 'Maintenance export generated by Vehicle Vitals.',
      ),
    );
  }

  // Export maintenance history as PDF
  Future<void> exportMaintenanceAsPDF(String vin) async {
    final maintenanceData = await _getMaintenanceData(vin);
    final vehicle = await _getVehicle(vin);

    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Text('Vehicle Vitals - Maintenance Report'),
            ),
            pw.Text('VIN: $vin'),
            pw.Text(
              'Vehicle: ${vehicle?['year'] ?? ''} ${vehicle?['make'] ?? ''} ${vehicle?['model'] ?? ''}',
            ),
            pw.SizedBox(height: 12),
            pw.TableHelper.fromTextArray(
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              cellAlignment: pw.Alignment.centerLeft,
              headers: ['Date', 'Title', 'Cost', 'Notes'],
              data: maintenanceData
                  .map(
                    (entry) => [
                      _isoDate(entry['date']),
                      (entry['title'] ?? '').toString(),
                      '\$${((entry['cost'] ?? 0) as num).toStringAsFixed(2)}',
                      (entry['notes'] ?? '').toString(),
                    ],
                  )
                  .toList(),
            ),
          ];
        },
      ),
    );

    final exportDir = await _exportDirectory();
    final fileName =
        'maintenance-$vin-${DateTime.now().millisecondsSinceEpoch}.pdf';
    final file = File('${exportDir.path}/$fileName');
    await file.writeAsBytes(await pdf.save());

    await SharePlus.instance.share(
      ShareParams(
        files: [XFile(file.path)],
        subject: 'Vehicle Vitals Maintenance Report ($vin)',
        text: 'Maintenance PDF generated by Vehicle Vitals.',
      ),
    );
  }

  // Export all vehicles and their maintenance as comprehensive report
  Future<void> exportAllDataAsPDF() async {
    final vehiclesSnapshot = await _firestore
        .collection('users')
        .doc(_userId)
        .collection('vehicles')
        .get();

    final pdf = pw.Document();

    for (final vehicleDoc in vehiclesSnapshot.docs) {
      final vehicle = vehicleDoc.data();
      final vin = vehicleDoc.id;
      final maintenanceData = await _getMaintenanceData(vin);

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          build: (context) {
            return [
              pw.Header(level: 0, child: pw.Text('Vehicle - $vin')),
              pw.Text(
                'Vehicle: ${vehicle['year'] ?? ''} ${vehicle['make'] ?? ''} ${vehicle['model'] ?? ''}',
              ),
              pw.Text('Mileage: ${(vehicle['mileage'] ?? 0).toString()}'),
              pw.SizedBox(height: 12),
              pw.TableHelper.fromTextArray(
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                cellAlignment: pw.Alignment.centerLeft,
                headers: ['Date', 'Title', 'Cost', 'Notes'],
                data: maintenanceData
                    .map(
                      (entry) => [
                        _isoDate(entry['date']),
                        (entry['title'] ?? '').toString(),
                        '\$${((entry['cost'] ?? 0) as num).toStringAsFixed(2)}',
                        (entry['notes'] ?? '').toString(),
                      ],
                    )
                    .toList(),
              ),
            ];
          },
        ),
      );
    }

    final exportDir = await _exportDirectory();
    final fileName =
        'maintenance-all-${DateTime.now().millisecondsSinceEpoch}.pdf';
    final file = File('${exportDir.path}/$fileName');
    await file.writeAsBytes(await pdf.save());

    await SharePlus.instance.share(
      ShareParams(
        files: [XFile(file.path)],
        subject: 'Vehicle Vitals Full Data Export',
        text: 'Comprehensive maintenance report generated by Vehicle Vitals.',
      ),
    );
  }

  // Helper method to get maintenance data for a vehicle
  Future<List<Map<String, dynamic>>> _getMaintenanceData(String vin) async {
    final maintenanceSnapshot = await _firestore
        .collection('users')
        .doc(_userId)
        .collection('vehicles')
        .doc(vin)
        .collection('maintenance')
        .orderBy('date', descending: true)
        .get();

    return maintenanceSnapshot.docs.map((doc) {
      return {'id': doc.id, ...doc.data()};
    }).toList();
  }
}
