extend type MaintenanceRecord {
  """
  ✨ Implicit foreign key field based on `MaintenanceRecord`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "MaintenanceRecord.user", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `MaintenanceRecord`.`vehicle`. It must match the value of `Vehicle`.`vin`. See `@ref` for how to customize it.
  """
  vehicleVin: String! @fdc_generated(from: "MaintenanceRecord.vehicle", purpose: IMPLICIT_REF_FIELD)
}
extend type Reminder {
  """
  ✨ Implicit foreign key field based on `Reminder`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "Reminder.user", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Reminder`.`vehicle`. It must match the value of `Vehicle`.`vin`. See `@ref` for how to customize it.
  """
  vehicleVin: String! @fdc_generated(from: "Reminder.vehicle", purpose: IMPLICIT_REF_FIELD)
}
extend type Vehicle {
  """
  ✨ Implicit foreign key field based on `Vehicle`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "Vehicle.user", purpose: IMPLICIT_REF_FIELD)
}
