extend type Mutation {
  """
  ✨ Insert a single `MaintenanceRecord` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  maintenanceRecord_insert(
    """
    Data object to insert into the table.
    """
    data: MaintenanceRecord_Data!
  ): MaintenanceRecord_KeyOutput! @fdc_generated(from: "MaintenanceRecord", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `MaintenanceSchedule` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  maintenanceSchedule_insert(
    """
    Data object to insert into the table.
    """
    data: MaintenanceSchedule_Data!
  ): MaintenanceSchedule_KeyOutput! @fdc_generated(from: "MaintenanceSchedule", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Reminder` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  reminder_insert(
    """
    Data object to insert into the table.
    """
    data: Reminder_Data!
  ): Reminder_KeyOutput! @fdc_generated(from: "Reminder", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Vehicle` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  vehicle_insert(
    """
    Data object to insert into the table.
    """
    data: Vehicle_Data!
  ): Vehicle_KeyOutput! @fdc_generated(from: "Vehicle", purpose: INSERT_SINGLE)
  """
  ✨ Insert `MaintenanceRecord` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  maintenanceRecord_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [MaintenanceRecord_Data!]!
  ): [MaintenanceRecord_KeyOutput!]! @fdc_generated(from: "MaintenanceRecord", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `MaintenanceSchedule` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  maintenanceSchedule_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [MaintenanceSchedule_Data!]!
  ): [MaintenanceSchedule_KeyOutput!]! @fdc_generated(from: "MaintenanceSchedule", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Reminder` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  reminder_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Reminder_Data!]!
  ): [Reminder_KeyOutput!]! @fdc_generated(from: "Reminder", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Vehicle` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  vehicle_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Vehicle_Data!]!
  ): [Vehicle_KeyOutput!]! @fdc_generated(from: "Vehicle", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `MaintenanceRecord` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MaintenanceRecord`.
  """
  maintenanceRecord_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: MaintenanceRecord_Data!
  ): MaintenanceRecord_KeyOutput! @fdc_generated(from: "MaintenanceRecord", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `MaintenanceSchedule` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MaintenanceSchedule`.
  """
  maintenanceSchedule_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: MaintenanceSchedule_Data!
  ): MaintenanceSchedule_KeyOutput! @fdc_generated(from: "MaintenanceSchedule", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Reminder` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Reminder`.
  """
  reminder_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Reminder_Data!
  ): Reminder_KeyOutput! @fdc_generated(from: "Reminder", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Vehicle` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Vehicle`.
  """
  vehicle_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Vehicle_Data!
  ): Vehicle_KeyOutput! @fdc_generated(from: "Vehicle", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `MaintenanceRecord` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MaintenanceRecord`.
  """
  maintenanceRecord_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [MaintenanceRecord_Data!]!
  ): [MaintenanceRecord_KeyOutput!]! @fdc_generated(from: "MaintenanceRecord", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `MaintenanceSchedule` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MaintenanceSchedule`.
  """
  maintenanceSchedule_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [MaintenanceSchedule_Data!]!
  ): [MaintenanceSchedule_KeyOutput!]! @fdc_generated(from: "MaintenanceSchedule", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Reminder` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Reminder`.
  """
  reminder_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Reminder_Data!]!
  ): [Reminder_KeyOutput!]! @fdc_generated(from: "Reminder", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Vehicle` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Vehicle`.
  """
  vehicle_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Vehicle_Data!]!
  ): [Vehicle_KeyOutput!]! @fdc_generated(from: "Vehicle", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `MaintenanceRecord` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `MaintenanceRecord` or `null` if not found.
  """
  maintenanceRecord_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MaintenanceRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MaintenanceRecord_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: MaintenanceRecord_Data!
  ): MaintenanceRecord_KeyOutput @fdc_generated(from: "MaintenanceRecord", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `MaintenanceSchedule` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `MaintenanceSchedule` or `null` if not found.
  """
  maintenanceSchedule_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MaintenanceSchedule_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MaintenanceSchedule_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: MaintenanceSchedule_Data!
  ): MaintenanceSchedule_KeyOutput @fdc_generated(from: "MaintenanceSchedule", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Reminder` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Reminder` or `null` if not found.
  """
  reminder_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Reminder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Reminder_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Reminder_Data!
  ): Reminder_KeyOutput @fdc_generated(from: "Reminder", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Vehicle` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Vehicle` or `null` if not found.
  """
  vehicle_update(
    """
    The key used to identify the object.
    """
    key: Vehicle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Vehicle_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Vehicle_Data!
  ): Vehicle_KeyOutput @fdc_generated(from: "Vehicle", purpose: UPDATE_SINGLE)
  """
  ✨ Update `MaintenanceRecord` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  maintenanceRecord_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: MaintenanceRecord_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: MaintenanceRecord_Data!
  ): Int! @fdc_generated(from: "MaintenanceRecord", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `MaintenanceSchedule` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  maintenanceSchedule_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: MaintenanceSchedule_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: MaintenanceSchedule_Data!
  ): Int! @fdc_generated(from: "MaintenanceSchedule", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Reminder` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  reminder_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Reminder_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Reminder_Data!
  ): Int! @fdc_generated(from: "Reminder", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Vehicle` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  vehicle_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Vehicle_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Vehicle_Data!
  ): Int! @fdc_generated(from: "Vehicle", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `MaintenanceRecord` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  maintenanceRecord_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MaintenanceRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MaintenanceRecord_FirstRow
  ): MaintenanceRecord_KeyOutput @fdc_generated(from: "MaintenanceRecord", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `MaintenanceSchedule` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  maintenanceSchedule_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MaintenanceSchedule_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MaintenanceSchedule_FirstRow
  ): MaintenanceSchedule_KeyOutput @fdc_generated(from: "MaintenanceSchedule", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Reminder` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  reminder_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Reminder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Reminder_FirstRow
  ): Reminder_KeyOutput @fdc_generated(from: "Reminder", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Vehicle` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  vehicle_delete(
    """
    The key used to identify the object.
    """
    key: Vehicle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Vehicle_FirstRow
  ): Vehicle_KeyOutput @fdc_generated(from: "Vehicle", purpose: DELETE_SINGLE)
  """
  ✨ Delete `MaintenanceRecord` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  maintenanceRecord_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: MaintenanceRecord_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "MaintenanceRecord", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `MaintenanceSchedule` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  maintenanceSchedule_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: MaintenanceSchedule_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "MaintenanceSchedule", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Reminder` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  reminder_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Reminder_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Reminder", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Vehicle` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  vehicle_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Vehicle_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle", purpose: DELETE_MULTIPLE)
}
