extend type Query {
  """
  ✨ Look up a single `MaintenanceRecord` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  maintenanceRecord(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MaintenanceRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MaintenanceRecord_FirstRow
  ): MaintenanceRecord @fdc_generated(from: "MaintenanceRecord", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `MaintenanceSchedule` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  maintenanceSchedule(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MaintenanceSchedule_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MaintenanceSchedule_FirstRow
  ): MaintenanceSchedule @fdc_generated(from: "MaintenanceSchedule", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Reminder` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  reminder(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Reminder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Reminder_FirstRow
  ): Reminder @fdc_generated(from: "Reminder", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Vehicle` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  vehicle(
    """
    The key used to identify the object.
    """
    key: Vehicle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Vehicle_FirstRow
  ): Vehicle @fdc_generated(from: "Vehicle", purpose: QUERY_SINGLE)
  """
  ✨ List `MaintenanceRecord` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  maintenanceRecords(
    """
    Filter condition to narrow down the query results.
    """
    where: MaintenanceRecord_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MaintenanceRecord_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MaintenanceRecord_Having
  ): [MaintenanceRecord!]! @fdc_generated(from: "MaintenanceRecord", purpose: QUERY_MULTIPLE)
  """
  ✨ List `MaintenanceSchedule` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  maintenanceSchedules(
    """
    Filter condition to narrow down the query results.
    """
    where: MaintenanceSchedule_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MaintenanceSchedule_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MaintenanceSchedule_Having
  ): [MaintenanceSchedule!]! @fdc_generated(from: "MaintenanceSchedule", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Reminder` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  reminders(
    """
    Filter condition to narrow down the query results.
    """
    where: Reminder_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Reminder_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Reminder_Having
  ): [Reminder!]! @fdc_generated(from: "Reminder", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Vehicle` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  vehicles(
    """
    Filter condition to narrow down the query results.
    """
    where: Vehicle_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Vehicle_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Vehicle_Having
  ): [Vehicle!]! @fdc_generated(from: "Vehicle", purpose: QUERY_MULTIPLE)
}
