#!/bin/bash
# 🌍 Vehicle-Vitals - Environment & Secret Management System
# CRITICAL: Bash 3.2 compatible - NO associative arrays

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; PURPLE='\033[0;35m'; NC='\033[0m'

# Helper functions
log_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }
log_success() { echo -e "${GREEN}✅ $1${NC}"; }
log_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; }
log_header() { echo -e "${PURPLE}🌍 $1${NC}"; echo -e "${PURPLE}$(printf '%.0s=' {1..50})${NC}"; }

# CRITICAL: Bash 3.2 compatibility - NO associative arrays
# Use variable naming convention: ENV_CONFIGS_<environment>
ENV_CONFIGS_development="vehicle-vitals-dev"
ENV_CONFIGS_staging="vehicle-vitals-staging"
ENV_CONFIGS_production="vehicle-vitals-prod"

# Validate environment
validate_environment() {
    local env="$1"
    case "$env" in
        development|staging|production) return 0 ;;
        *) log_error "Invalid environment: $env"; exit 1 ;;
    esac
}

# Get Firebase project (Bash 3.2 compatible)
get_firebase_project() {
    local env="$1"
    eval "echo \$ENV_CONFIGS_$env"
}

# Generate secure secrets
generate_secret() { openssl rand -hex "${1:-32}"; }
generate_password() { openssl rand -base64 "${1:-24}" | tr -d "=+/" | cut -c1-"${1:-24}"; }

# Environment file management
manage_env_files() {
    local env="$1"
    log_header "Environment File Management - $env"

    # Create environment-specific .env file
    local env_file=".env.$env"
    local firebase_project
    eval "firebase_project=\$ENV_CONFIGS_$env"

    if [ ! -f "$env_file" ]; then
        log_info "Creating $env_file..."

        cat > "$env_file" << EOF
# Vehicle-Vitals - $env Environment Configuration
# Auto-generated by automation system

# Firebase Configuration
VITE_FIREBASE_API_KEY=your-api-key
VITE_FIREBASE_AUTH_DOMAIN=${firebase_project}.firebaseapp.com
VITE_FIREBASE_PROJECT_ID=${firebase_project}
VITE_FIREBASE_STORAGE_BUCKET=${firebase_project}.appspot.com
VITE_FIREBASE_MESSAGING_SENDER_ID=your-sender-id
VITE_FIREBASE_APP_ID=your-app-id

# Environment
NODE_ENV=$env
VITE_ENVIRONMENT=$env

# API Configuration
VITE_API_BASE_URL=https://us-central1-${firebase_project}.cloudfunctions.net/api

# Security
VITE_JWT_SECRET=$(generate_secret 32)
VITE_ENCRYPTION_KEY=$(generate_secret 32)

# Development settings
VITE_DEBUG_MODE=false
EOF

        log_success "Created $env_file"
        log_warning "Please update the Firebase configuration values in $env_file"
    else
        log_info "$env_file already exists"
    fi
}

# GitHub Secrets management
manage_github_secrets() {
    local env="$1"
    log_header "GitHub Secrets Management - $env"

    # Check GitHub CLI authentication
    if ! command -v gh >/dev/null 2>&1; then
        log_error "GitHub CLI not installed"
        exit 1
    fi

    if ! gh auth status >/dev/null 2>&1; then
        log_error "GitHub CLI not authenticated. Run: gh auth login"
        exit 1
    fi

    # Get repository info
    local repo_owner="${GITHUB_REPO%/*}"
    local repo_name="${GITHUB_REPO#*/}"

    if [ -z "$repo_owner" ] || [ -z "$repo_name" ]; then
        log_error "GITHUB_REPO not properly configured in .env.automation.$env"
        exit 1
    fi

    log_info "Managing secrets for $repo_owner/$repo_name"

    # Environment-specific secrets
    local firebase_project
    eval "firebase_project=\$ENV_CONFIGS_$env"

    # Set Firebase service account key
    if [ -n "$FIREBASE_SERVICE_ACCOUNT_KEY" ]; then
        log_info "Setting FIREBASE_SERVICE_ACCOUNT_KEY..."
        echo "$FIREBASE_SERVICE_ACCOUNT_KEY" | gh secret set FIREBASE_SERVICE_ACCOUNT_KEY \
            --repo "$repo_owner/$repo_name" --env "$env"
    fi

    # Set Firebase project ID
    if [ -n "$firebase_project" ]; then
        log_info "Setting FIREBASE_PROJECT_ID..."
        echo "$firebase_project" | gh secret set FIREBASE_PROJECT_ID \
            --repo "$repo_owner/$repo_name" --env "$env"
    fi

    # Set other secrets based on environment
    case "$env" in
        "production")
            # Production-specific secrets
            if [ -n "$SMTP_PASS" ]; then
                log_info "Setting SMTP_PASS..."
                echo "$SMTP_PASS" | gh secret set SMTP_PASS \
                    --repo "$repo_owner/$repo_name" --env "$env"
            fi

            if [ -n "$JWT_SECRET" ]; then
                log_info "Setting JWT_SECRET..."
                echo "$JWT_SECRET" | gh secret set JWT_SECRET \
                    --repo "$repo_owner/$repo_name" --env "$env"
            fi

            if [ -n "$ENCRYPTION_KEY" ]; then
                log_info "Setting ENCRYPTION_KEY..."
                echo "$ENCRYPTION_KEY" | gh secret set ENCRYPTION_KEY \
                    --repo "$repo_owner/$repo_name" --env "$env"
            fi
            ;;
    esac

    log_success "GitHub secrets synchronized for $env environment"
}

# Show environment status
show_status() {
    local env="$1"
    log_header "Environment Status - $env"

    # Check if environment files exist
    local env_file=".env.$env"
    if [ -f "$env_file" ]; then
        log_success "Environment file exists: $env_file"
    else
        log_warning "Environment file missing: $env_file"
    fi

    # Check Firebase project
    local firebase_project
    eval "firebase_project=\$ENV_CONFIGS_$env"
    if [ -n "$firebase_project" ]; then
        log_info "Firebase project: $firebase_project"

        # Check if Firebase project exists
        if firebase projects:list 2>/dev/null | grep -q "$firebase_project"; then
            log_success "Firebase project exists and is accessible"
        else
            log_warning "Firebase project may not exist or is not accessible"
        fi
    else
        log_error "Firebase project not configured for $env"
    fi

    # Check GitHub secrets (if authenticated)
    if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
        local repo_owner="${GITHUB_REPO%/*}"
        local repo_name="${GITHUB_REPO#*/}"

        if [ -n "$repo_owner" ] && [ -n "$repo_name" ]; then
            log_info "Checking GitHub secrets for $repo_owner/$repo_name..."

            # This is a simplified check - in practice you'd want to verify specific secrets
            if gh api "repos/$repo_owner/$repo_name/actions/secrets" >/dev/null 2>&1; then
                log_success "GitHub repository accessible"
            else
                log_warning "Cannot access GitHub repository secrets"
            fi
        fi
    else
        log_warning "GitHub CLI not available or not authenticated"
    fi
}

# Setup environment
setup_environment() {
    local env="$1"
    log_header "Setting up Environment - $env"

    # Validate environment
    validate_environment "$env"

    # Create environment files
    manage_env_files "$env"

    # Setup Firebase project if it doesn't exist
    local firebase_project
    eval "firebase_project=\$ENV_CONFIGS_$env"

    if [ -n "$firebase_project" ]; then
        log_info "Checking Firebase project: $firebase_project"

        if ! firebase projects:list 2>/dev/null | grep -q "$firebase_project"; then
            log_warning "Firebase project $firebase_project does not exist"
            log_info "Please create the Firebase project manually or update ENV_CONFIGS_$env"
        else
            log_success "Firebase project $firebase_project exists"

            # Use the project
            firebase use "$firebase_project"

            # Initialize Firebase services for the project
            log_info "Initializing Firebase services..."
            # Note: This would typically be done once per project
            # firebase init hosting functions firestore --project "$firebase_project"
        fi
    fi

    log_success "Environment setup completed for $env"
}

# Main function
main() {
    local action="${1:-status}"
    local environment="${2:-development}"

    # Change to project root
    cd "$PROJECT_ROOT"

    # Load configuration
    local automation_env_file=".env.automation.${environment}"
    if [ -f "$automation_env_file" ]; then
        source "$automation_env_file"
    elif [ -f ".env.automation" ]; then
        source .env.automation
    fi

    case "$action" in
        "setup")
            setup_environment "$environment"
            ;;
        "sync-secrets")
            manage_github_secrets "$environment"
            ;;
        "status")
            show_status "$environment"
            ;;
        *)
            log_error "Unknown action: $action"
            log_info "Available actions: setup, sync-secrets, status"
            exit 1
            ;;
    esac
}

main "$@"
